services:
  bind9:
    image: ubuntu/bind9
    container_name: servidor

    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      bind9_subnet_asir2:
        ipv4_address: 172.28.5.1
    volumes:
      - ./conf:/etc/bind 
      - ./zonas:/var/lib/bind
    environment:
      - TZ=Europe/Paris

  cliente:
    container_name: cliente
    image: alpine
    tty: true
    stdin_open: true
    dns:
      - 172.28.5.1
    networks:
      bind9_subnet_asir2:
        ipv4_address: 172.28.5.2

networks:
  bind9_subnet_asir2:
    external: true

